---
- hosts: localhost
  connection: local
  become: true
  
  - name: install packages (Debian)
    when: ansible_os_family == "Debian"
    package:
      name:
        - fish
        - htop
        - nano
        - vim-nox
        - python3-psutil
        - sshfs
        - cifs-utils
        - python3-pip

  - name: install packages (Arch)
    when: ansible_os_family == "Archlinux"
    package:
      name:
        - fish
        - htop
        - nano
        - vim
        - sshfs
        - cifs-utils
        - cronie

  - name: enable cronie (Arch)
    when: ansible_os_family == "Archlinux"
    systemd:
      name: cronie
      enabled: yes
      state: started

#  - name: add yaml syntax highlighting to vimrc
#    lineinfile:
#      path: /home/trevor/.vimrc
#      line: "autocmd FileType yaml setlocal ai ts=2 sw=2 et"
#      state: present

  - name: copy nanorc folder
    copy:
      src: files/nano/
      dest: /home/trevor/.nano/
      remote_src: yes
      directory_mode: yes
      owner: trevor
      group: trevor

  - name: copy nanorc folder
    copy:
      src: files/nanorc
      dest: /home/trevor/.nanorc
      remote_src: yes
      owner: trevor
      group: trevor

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: trevor
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: trevor
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/trevor/.bashrc
      owner: trevor
      group: trevor


  - name: add ansible user
    user:
      name: awx
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_awx
      dest: /etc/sudoers.d/awx
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: awx
      hour: "*/6"
      job: ansible-pull -o -U https://github.com/tangowithfoxtrot/ansible_workstation_config.git
